# Generated by Django 2.2.1 on 2019-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
