# Generated by Django 2.2.1 on 2019-05-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190519_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='update_time',
            new_name='update_date',
        ),
    ]
